[package]
name = "qubx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
concurrent-queue = "2.4.0"
portaudio = "0.7.0"
threadpool = "1.8.1"
